[phases.setup]
nixPkgs = ["nodejs_18", "ffmpeg", "python3", "libtool", "autoconf", "automake", "pkg-config", "libsodium"]

[phases.install]
cmds = [
  "PYTHON=python3 npm install --omit=optional --legacy-peer-deps"
]

[start]
cmd = "npm start"
